Update to include thirdweb-dev & thridwed-examples
thirdweb-dev/dashboard pull request #1155
Opened 2023-04-28 14:19 UTC by BankkRoll

Update response to include thirdweb-dev & thridwed-examples to show all "Top Community Contributors"

2023-05-01 06:36 UTC, jarrodwatts commented
Great idea @BankkRoll!

This looks good to me  - will get a second opinion from one of our engineers before merging

2023-05-01 15:46 UTC, BankkRoll commented
> Great idea @BankkRoll!
> 
> This looks good to me - will get a second opinion from one of our engineers before merging


Thanks @jarrodwatts!
I took note of the filter in the repo results. Made sure we didn't need to filter some from examples :)

2023-05-10 15:34 UTC, jnsdls requested changes
fix merge conflicts and parallelize requests then ship

2023-05-10 15:34 UTC, jnsdls commented on pages/open-source.tsx
> +  for (const account of accounts) {
could do this simultaneously instead of one at a time (use promise all, merge the results and then process them all together)

2023-05-10 15:34 UTC, jnsdls commented on pages/open-source.tsx
> +    for (const repo of repos) {
same thing here this should be done in parallel instead of one at a time (using promise.all)

2023-05-11 01:24 UTC, jarrodwatts commented
Hey @BankkRoll - feel free to ping me on Discord if you have any questions on these!

2023-05-11 02:12 UTC, BankkRoll commented
> Hey @BankkRoll - feel free to ping me on Discord if you have any questions on these!

Hey sounds good just seeing this, will get a look and update this

2023-05-11 02:47 UTC, closed without merging

2023-05-11 02:55 UTC, BankkRoll commented
@jarrodwatts idk what i did lol im tired and closed it again... ill go back and update it and sumbit the pr again or reopen this tomorrow to tired tonight, i accidently closed it trying to sync and merge the new updates.

2023-05-12 16:46 UTC, BankkRoll commented
Hey @jarrodwatts not sure if that was good enough but best way I figured out how to fix whatever I did. and swapped the fetching to use promise all updated pr #1200 , also mentioned this PR