added ambassador page - initial version
thirdweb-dev/dashboard pull request #1221
Opened 2023-05-19 20:21 UTC by saminacodes

2023-05-19 20:26 UTC, jnsdls commented
#### 📝 Changed routes:


| [**/ambassadors**](https://thirdweb-66kgneok2.thirdweb-preview.com/ambassadors) |
|:-:|
|<a href="https://thirdweb-66kgneok2.thirdweb-preview.com/ambassadors"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/uITkl2BhY5LMxGc-gWF5LpzHqnGjKH5t0uBFFdzrW6mpu1RMNgPFztnjXAhorv7AkHU3bEFheMtm2xyDNbY2Dw.png&w=600" alt="Screenshot of /ambassadors" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/GHi2_B5zFXN7FDGDlZv6XjM2YOE6-BTQt9mD3bFCfhQUAmHpiXbqd8edHyfTO7WiR9ksyTItoV4xMajKRPzN6w.png">(view full size)</a> |







Commit f9146185cd6a9683e1dfe48b6238674e68de3266 (https://thirdweb-66kgneok2.thirdweb-preview.com).

2023-05-22 18:15 UTC, nachoiacovino requested changes
pretty close to be able to ship, need some updates and add a link to the menu/mobile menu/footer

2023-05-22 18:15 UTC, nachoiacovino commented on pages/ambassadors.tsx
> +                      category: "cta-button",
category should be defined at the top with something like `const CATEGORY = "ambassadors_page"` then use throughout the page

2023-05-22 18:15 UTC, nachoiacovino commented on pages/ambassadors.tsx
> +                      label: "ambassador",
```suggestion
                      label: "join-the-community",
```

no need for title

2023-05-22 18:15 UTC, nachoiacovino commented on components/devRelEvents/AmbassadorCards.tsx
> +        fontSize="body.lg"
basically if you only ever gonna have Text, just wrap the children with `Text` and add a size prop

2023-05-22 18:15 UTC, nachoiacovino commented on pages/ambassadors.tsx
> +                        no twitter
isn't it better to just not render anything if they don't have twitter?

2023-05-22 18:15 UTC, nachoiacovino commented on pages/ambassadors.tsx
> +                        category="team"
change the category to `ambassadors`

2023-05-22 18:15 UTC, nachoiacovino commented on pages/ambassadors.tsx
> +                  columns={{ base: 1, md: 5 }}
maybe add `sm: 3` too?

2023-05-22 18:15 UTC, nachoiacovino commented on components/devRelEvents/AmbassadorCards.tsx
> +      borderRadius="16px"
I mean in general instead of px values

2023-05-25 15:32 UTC, saminacodes commented on page-id.ts
unsure why that happened

2023-05-30 23:44 UTC, nachoiacovino commented on pages/ambassadors.tsx
> +                        no twitter
feels bad we're copy pasting instead of making it it's own component if it's the same but oh well, just leave it then

2023-05-30 23:45 UTC, nachoiacovino commented on components/devRelEvents/AmbassadorCards.tsx
> +        <Text fontSize="body.lg">{children}</Text>
this should be size

2023-05-30 23:45 UTC, nachoiacovino commented on page-id.ts
what's going on here with the spaces? :D

2023-05-30 23:46 UTC, nachoiacovino commented
please fix the build, the display.lg can only be assigned to `Heading`

2023-05-31 17:50 UTC, merged