feat: Contract subscriptions filters
thirdweb-dev/dashboard pull request #2653
Opened 2024-06-13 01:40 UTC by arcoraven

- Allow CRUD for contract subscription filters
- What are filters? The dev can select whether or not to enable logs or receipts.
  - For logs, they can listen to all events for specific events.
  - For receipts, they can listen to all functions or specific functions.

2024-06-13 01:41 UTC, arcoraven commented on src/hooks/useContractAbiItems.ts
> +export const useContractAbiItems = (
I'm not familiar with writing hooks. Please look at this.

2024-06-13 01:43 UTC, arcoraven commented
Some screenshots

![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/f574c1d4-b4e2-4d40-87fa-17bef5e56b5c)
![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/2fcc2d69-cb01-40aa-8bed-967a5405dc73)
![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/c9cd133d-8706-4609-94c3-77a46aa436ac)
![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/1a4298d2-513c-430b-97cf-f1c9365f08df)
![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/a7140bca-af2e-4317-9a6c-83d208cfd951)
![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/31f917fe-5157-4bb6-a61b-fee5522ca61e)
![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/31e4e75f-d053-463a-a441-cfbddab921d4)
![image](https://github.com/thirdweb-dev/dashboard/assets/7673418/b8813799-77bd-4114-a628-abce6fba0458)

2024-06-13 06:09 UTC, jnsdls commented on src/hooks/useContractAbiItems.ts
> +  return { readFunctions, writeFunctions, events };
this entire thing should be a `useQuery` instead: `chainId` and `contractAddress` should be part of the query key

something along these lines (rough):
```
const {data, isLoading} = useQuery({
  queryKey: ['contract-abi-items', chainId, address],
  queryFn: async () => {
// ... your async logic here, return the readFunctions, writeFunctions, events from it at the end
})

return data;
```

2024-06-13 06:53 UTC, arcoraven commented on src/components/engine/contract-subscription/add-contract-subscription-button.tsx
> +    const formData = form.getValues();
This modal has two pages/steps, so I wasn't sure if wrapping the modal in a form made sense. I guess it does.

2024-06-14 01:32 UTC, jnsdls commented
* **#2653** <a href="https://app.graphite.dev/github/pr/thirdweb-dev/dashboard/2653?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arcoraven and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-14 01:49 UTC, jnsdls requested changes
fixed the useQuery - just the form left

2024-06-14 01:49 UTC, jnsdls commented on src/components/engine/contract-subscription/add-contract-subscription-button.tsx
> +    const formData = form.getValues();
yeah it does

2024-06-14 20:20 UTC, jnsdls approved these changes
LGTM

2024-06-18 07:45 UTC, merged