Use custom contract pages for token contracts
thirdweb-dev/dashboard pull request #381
Opened 2022-08-15 23:07 UTC by nachoiacovino

2022-08-15 23:09 UTC, jnsdls commented
#### 📝 Changed routes:


| [**/dashboard**](https://thirdweb-adfn38e0z-thirdweb.vercel.app/dashboard) |
|:-:|
|<a href="https://thirdweb-adfn38e0z-thirdweb.vercel.app/dashboard"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/rh5FP8p6xTWa-NZ9fPoig0MSh39DPHrSs9fumgyspBxRX8thR-Z-vuJeKFJ8-lQboGT35a3qJrP3UhT2I_kXCA.png&w=600" alt="Screenshot of /dashboard" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/2gLkg7hjCxBDFuW4D7jpO2qMjd55NWCUKpA9rJRfuN5wZWqwiinShiGaVNYKc0wLvyqcLweAK23oqGJFEBLP1Q.png">(view full size)</a> |







Commit 85b3bf8fbe41fdc16333b398a65d8ef0cc62771a (https://thirdweb-adfn38e0z-thirdweb.vercel.app).

2022-08-16 16:18 UTC, jnsdls requested changes
small fixes

2022-08-16 16:18 UTC, jnsdls commented on constants/mappings.ts
>  };
this change scares me, I would love to leave this all as is and fix it in the one spot where it causes problems

2022-08-16 16:18 UTC, jnsdls commented on components/contract-components/contract-deploy-form/built-in-contract.tsx
> +                `/${SupportedChainIdToNetworkMap[selectedChain]}${UrlMap[contractType]}/${contractAddress}`,
could we just fix it in this spot? could we just do a `.replaceAll("//", "/")` and be done with it?

2022-08-16 16:18 UTC, jnsdls commented on pages/dashboard/index.tsx
> +    cell.contractType === "custom" ? "" : `${UrlMap[cell.contractType]}`;
if we can solve it the other way then we can get rid of this change

2022-08-16 16:18 UTC, jnsdls commented on constants/mappings.ts
>  };
scares me because I don't have a good overview of where else this might be used if that makes sense

2022-08-16 16:20 UTC, nachoiacovino commented
we would need to fix it or do the replace in different places @jnsdls, we can do that definitely but it made more sense to me like this.

2022-08-16 16:36 UTC, jnsdls approved these changes
LGTM, @nachoiacovino make sure it all works, otherwise u fix it

2022-08-16 16:47 UTC, merged