Release flow improvements
thirdweb-dev/dashboard pull request #412
Opened 2022-08-24 16:02 UTC by nachoiacovino

Fixes FTD-772, FTD-676, FTD-771 and FTD-713

2022-08-26 21:19 UTC, jnsdls requested changes
I don't think we want release logos to be hexagons

2022-08-26 21:19 UTC, jnsdls commented on components/contract-components/contract-release-form/index.tsx
> +                  )}
@nachoiacovino why would the contract image be a hexagon?

2022-08-26 21:19 UTC, jnsdls commented on components/pages/release.tsx
> +            />
why do releases have hex images?

2022-08-29 14:01 UTC, nachoiacovino commented on components/pages/release.tsx
> +            />
no reason I guess, changed

2022-08-29 19:05 UTC, jnsdls approved these changes
LGTM

2022-08-29 19:12 UTC, merged