feat: build gaming hackathon landing
thirdweb-dev/dashboard pull request #740
Opened 2022-12-14 08:24 UTC by avneesh0612

2022-12-16 08:57 UTC, jnsdls submitted a review, later dismissed

2022-12-16 08:57 UTC, jnsdls commented on components/hackathon/common/PrizeSection.tsx
> +}
this should be `PrizeSectionProps` based on how we generally name props types

also I would recommend extracting `Prize` as a type here so then it becomes `prizes: Prize[]` **or** alternatively using the `Array<{...}` syntax to make this more readable

2022-12-16 08:57 UTC, jnsdls commented on components/hackathon/common/PrizeSection.tsx
> +              </Center>
is this not just the same as giving the `Divider` a `my={7}` ?

2022-12-16 08:57 UTC, jnsdls commented on components/hackathon/common/ScheduleSection.tsx
> +}
same comment about the naming of the interface and extracting or array syntax for the items

2022-12-16 08:57 UTC, jnsdls commented on components/hackathon/common/Sponsors.tsx
> +}
same comment about the naming of the interface and extracting or array syntax for the items

2022-12-16 08:57 UTC, jnsdls commented on components/hackathon/common/Sponsors.tsx
> +            category="solanathon"
this category can no longer be hard-coded, right? Has to be passed in now since it's re-usable?

2022-12-16 08:57 UTC, jnsdls commented on components/hackathon/common/Timer.tsx
> +interface ITimerProps {
should be TimerProps

2022-12-16 09:04 UTC, jnsdls commented on components/hackathon/common/Sponsors.tsx
> +            category="solanathon"
this part is a blocker, the rest could be improved later on

2022-12-16 11:29 UTC, nachoiacovino requested changes
Some fixes needed:

![image](https://user-images.githubusercontent.com/50103937/208088243-6d6878b4-b7ab-4ecd-8776-29d34e7d74f6.png)

These logos all need to be with white text or fill the svg with white text, otherwise they're unreadable. 

![image](https://user-images.githubusercontent.com/50103937/208088319-113d74b6-6306-4e8b-8da2-28016a5140fc.png)

This FAQ doesn't work on mobile correctly. 

![image](https://user-images.githubusercontent.com/50103937/208088399-7f79b08e-4778-4b9f-8654-7ae68967276a.png)

If this schedule doesn't link anywhere, please remove the pointer events if there's no href, otherwise it refreshes the page when you click into it. 

The submissions requirements seem super long but imo and could use some spacing between title and text

2022-12-16 15:24 UTC, avneesh0612 commented
yea @nachoiacovino still working on these fixes that's why I made the pr a draft :p

2022-12-16 15:24 UTC, avneesh0612 commented
and for the judges part no. Pat will be providing me with the judges soon

2023-01-05 15:01 UTC, nachoiacovino approved these changes
letsshipit

2023-01-05 15:04 UTC, merged