Overhaul product pages
thirdweb-dev/dashboard pull request #791
Opened 2023-01-13 04:22 UTC by shift4id

2023-01-13 21:11 UTC, jnsdls commented
#### 📝 Changed routes:


| [**/dashboards**](https://thirdweb-jy24k0399.thirdweb-preview.com/dashboards) | [**/storage**](https://thirdweb-jy24k0399.thirdweb-preview.com/storage) |
|:-:|:-:|
|<a href="https://thirdweb-jy24k0399.thirdweb-preview.com/dashboards"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/HslG9ixBCN8ZDUQiGL3Cp73qAzvlb-TlVlcYXmalJSxwa8p8UHgTOmHvwJjsnK3XgMFJVsuCn7_UJ8PZzU2Akw.png&w=600" alt="Screenshot of /dashboards" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/u_1H-uqiceOK0vBfEzLTFc0y4QMIZOoW0PFjwPF3NxTOKMkuz8qNbmfkz79gSUWTrfsyaKnZqjS_oQrAdKnaFA.png">(view full size)</a> |<a href="https://thirdweb-jy24k0399.thirdweb-preview.com/storage"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/a3rsKVvJxTqru7OtZarDZ-GNyW8JzMwwTJx6beA3XAthEnOBUgU2XXm3QjGgm3EGMmMnHfHGGmBItPt0XrmuWw.png&w=600" alt="Screenshot of /storage" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Ms_6LL4xoL8E3ZdPwQqbQSAkyvllVWnU3q2nNFG8bm52_n-_Ooixh-TAvIXB0jk_WUVGkHiVv_dm2yP5nfBJ9g.png">(view full size)</a> |



| [**/ui-components**](https://thirdweb-jy24k0399.thirdweb-preview.com/ui-components) |
|:-:|
|<a href="https://thirdweb-jy24k0399.thirdweb-preview.com/ui-components"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/bQ7eCg99Adr00kHWug1avZm8X48j6KTvsiHsbrcqyWi-TQyDev15oYOQH0UvE1u3sVCqhh6UKw4LKr4NQ5CMRg.png&w=600" alt="Screenshot of /ui-components" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/tl-knpCV4G8RqOVIuNC72k7SZQkWCiGvTZkIjnr_l1fXdnRyGm9Y5haVIJCNxipA8DvhjT18yYt7M2XXKX5AZA.png">(view full size)</a> |







Commit 52d5c053945687a9538007482279356a60570e0f (https://thirdweb-jy24k0399.thirdweb-preview.com).

2023-01-14 01:59 UTC, nachoiacovino requested changes
biggest issue is that on all three pages the divider doesn't have padding with the product cards, that needs to be fixed before shipping

![image](https://user-images.githubusercontent.com/50103937/212445618-aed0b66e-22b6-4972-9a0e-45e6b9f54dab.png)

2023-01-14 01:59 UTC, nachoiacovino commented on components/product-pages/common/ProductLearnMoreCard.tsx
> +          {icon && (
can we just get a random icon from any other page instead of doing this?

2023-01-14 01:59 UTC, nachoiacovino commented on pages/dashboards.tsx
> +const GUIDES = [
can we get a third guide here? there's a lot of guides about our dashboard

2023-01-14 01:59 UTC, nachoiacovino commented on pages/ui-components.tsx
> +          {/* TODO: Add headline to components section */}
can we get rid of the comments?

2023-01-16 19:31 UTC, nachoiacovino requested changes
issue with the border is still happening on /dashboards and /storage

2023-01-16 19:31 UTC, nachoiacovino commented on pages/ui-components.tsx
> +            {/* <Heading*/}
can we either add a headline or get rid of the comment?

2023-01-16 20:01 UTC, nachoiacovino approved these changes
lgtm!

2023-01-16 20:13 UTC, merged